### ISSUE TITLE
Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.4:testCompileue 

### ISSUE THREAD

**Issue by SyCode7** [dataArtisans/flink-training#25]
Hi,

I have cloned this [repo ](https://github.com/dataArtisans/flink-training-exercises.git)as instructed [here](http://training.data-artisans.com/) in order to get familiar with Flink. However, there are the errors in the projects after building and importing into Eclipse IDE. In the `Flink Training Exercises` project  i find errors in the pom `Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.4:testCompile`.  There are also errors in the project `flink-quickstart-java` .  Some dependencies are not being resolved e.g. `ExecutionEnvironment cannot be resolved`  in the  `BatchJob` class.  I have tried to clean the `.m2` folder and complied both projects several times but there is no joy yet !

**Comment by alpinegizmo** [comment]
The quickstart was recently changed, which had an effect here. I got this working by selecting the add-dependencies-for-IDEA maven profile.

**Comment by SyCode7** [comment]
@alpinegizmo thanks for the heads up. The challenge is that  I am using eclipse, I am not sure if there is such a feature on eclipse ....are you aware of any ?

**Comment by alpinegizmo** [comment]
Yes, I did this with Eclipse. I added this section to &lt;build&gt; &lt;plugins&gt; in my pom file:

		<plugin>
		   <groupId>org.codehaus.mojo</groupId>
		   <artifactId>exec-maven-plugin</artifactId>
		   <version>1.6.0</version>
		   <executions>
		     <execution>
		       <goals>
		        <goal>java</goal>
		       </goals>
		    </execution>
		   </executions>
		   <configuration>
		      <mainClass>org.apache.flink.flink_quickstart_java.BatchJob</mainClass>
		   </configuration>
		</plugin>

and then created a Maven Build run configuration with 

    Goals: org.codehaus.mojo:exec-maven-plugin:java
    Profiles: add-dependencies-for-IDEA

**Comment by SyCode7** [comment]
@alpinegizmo  i have tried on eclipse, I have the following error : 


`[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ flink-java-project ---
[WARNING] 
java.lang.RuntimeException: No data sinks have been created yet. A program needs at least one sink that consumes data. Examples are writing the data set or printing it.
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:943)
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:921)
	at org.apache.flink.api.java.LocalEnvironment.execute(LocalEnvironment.java:85)
	at org.apache.flink.quickstart.BatchJob.main(BatchJob.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE`

**Comment by alpinegizmo** [comment]
Yes, the skeleton batch job isn't complete. You could modify it to be like this, and it will work:

    public class BatchJob {
        public static void main(String[] args) throws Exception {
		final ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();

		env.fromElements(1, 2, 3).print();
        }
    }

If instead you want to try streaming, do this:

    public class StreamingJob {
        public static void main(String[] args) throws Exception {
		StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

		env.fromElements(1, 2, 3).print();
		env.execute();
        }
    }

**Comment by SyCode7** [comment]
@alpinegizmo  many thanks. your solution works ! I realized that I have to ignore the errors shown in eclipse  .....very strange.
